### ISSUE TITLE
api-version missing from plugin.yml, triggers Legacy Support in Bukkit

### ISSUE THREAD

**Issue by ghost** [JoelGodOfwar/SilenceMobs#3]
### What behaviour is expected:
A clean console log, the plugin not triggering the Legacy Support in Bukkit and not being marked as legacy in the plugin menu.

### What behaviour is observed:
```
[18:27:10] [Server thread/WARN]: [org.bukkit.craftbukkit.v1_20_R3.legacy.CraftLegacy] Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
 88 [18:27:13] [Server thread/WARN]: Legacy plugin SilenceMobs v1.10_1.0.5 does not specify an api-version.
 89 [18:27:13] [Server thread/WARN]: Legacy plugin RecipeUnlocker v0.0.2 does not specify an api-version.
 90 [18:27:13] [Server thread/INFO]: [WorldEdit] Loading server plugin WorldEdit v7.2.18+6616-abda4e0
```

### Steps/models to reproduce:
Simply startup a Minecraft server with the plugin installed and observe the console log.

### Plugin list:
 ArmorStandEditor, MoreMobHeads, Multiverse-Core, RapidLeafDecay, *RecipeUnlocker, *SilenceMobs, VillagerWorkstationHighlights, WorldEdit, WorldGuard

### Bukkit/Spigot server version or Paper build number:
Paper version git-Paper-379 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 570cfb4)

**Comment by JoelGodOfwar** [comment]
api-version: 1.10 added to plugin.yml
